In [1]:
import numpy as np
x = np.arange(9).reshape(3, 3)
x = np.expand_dims(x, 0)
print(x.shape)
y = np.repeat(x, 3, 0)
y.shape

(1, 3, 3)


(3, 3, 3)

In [47]:
import torch
x = torch.rand(3, 3).numpy()

import torchvision.transforms as T
y = T.ToTensor()(x)

y = torch.LongTensor(range(80))


'''

'''
label = torch.LongTensor([4, 5, 6])

object_for_each_prior = torch.LongTensor([0, 1, 2, 2])
label[object_for_each_prior] 
'''
x[i] = label[i]

'''
import numpy as np
sx = np.arange(0, 100, 2)
sy = np.arange(0, 100, 4) 
smx, smy = np.meshgrid(sx, sy)

In [48]:
sx

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [49]:
smx

array([[ 0,  2,  4, ..., 94, 96, 98],
       [ 0,  2,  4, ..., 94, 96, 98],
       [ 0,  2,  4, ..., 94, 96, 98],
       ...,
       [ 0,  2,  4, ..., 94, 96, 98],
       [ 0,  2,  4, ..., 94, 96, 98],
       [ 0,  2,  4, ..., 94, 96, 98]])

In [53]:
smy

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 4,  4,  4, ...,  4,  4,  4],
       [ 8,  8,  8, ...,  8,  8,  8],
       ...,
       [88, 88, 88, ..., 88, 88, 88],
       [92, 92, 92, ..., 92, 92, 92],
       [96, 96, 96, ..., 96, 96, 96]])

In [2]:
np.arange(0, 416, 15).shape

(28,)

In [10]:
import torch
x = torch.LongTensor([0, 1, 3])

In [18]:
x = torch.rand(3, 3)
mask = (x > 0.5)
x[mask] = 0
x.fill_(0)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
x = torch.ones(5, 5, 5)
torch.sigmoid(x[...,:2])

tensor([[[0.7311, 0.7311],
         [0.7311, 0.7311],
         [0.7311, 0.7311],
         [0.7311, 0.7311],
         [0.7311, 0.7311]],

        [[0.7311, 0.7311],
         [0.7311, 0.7311],
         [0.7311, 0.7311],
         [0.7311, 0.7311],
         [0.7311, 0.7311]],

        [[0.7311, 0.7311],
         [0.7311, 0.7311],
         [0.7311, 0.7311],
         [0.7311, 0.7311],
         [0.7311, 0.7311]],

        [[0.7311, 0.7311],
         [0.7311, 0.7311],
         [0.7311, 0.7311],
         [0.7311, 0.7311],
         [0.7311, 0.7311]],

        [[0.7311, 0.7311],
         [0.7311, 0.7311],
         [0.7311, 0.7311],
         [0.7311, 0.7311],
         [0.7311, 0.7311]]])